# Generated by Django 4.2 on 2024-06-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.TextField(db_index=True, unique=True)),
                ("definition", models.TextField()),
                ("synonyms", models.TextField()),
                ("antonyms", models.TextField()),
                ("letterized_1", models.TextField()),
                ("letterized_2", models.TextField()),
                ("letterized_3", models.TextField()),
            ],
        ),
    ]
