# Generated by Django 4.2 on 2024-06-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_word_dont_know_word_known"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="rut",
            field=models.IntegerField(default=0),
        ),
    ]
