# Generated by Django 4.2 on 2024-07-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_word_rut"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="definitions",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="word",
            name="examples",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
